spring:
  data:
    rest:
      basePath: /api
  batch:
    job:
      enabled: true
server:
  context-path: /demo
logging:
  level: info
S3:
  AccessKey: 3PNA5CJTQS5YVGOM19IS
  SecretKey: 9bwacm7O0+ipmLfVc6JibHhe6UcZP5H+vtvjphQO


