spring:
  data:
    rest:
      basePath: /api
  batch:
    job:
      enabled: true
server:
  context-path: /demo
logging:
  level: info
S3:
  accessKey: xxxxxxxxxxx
  secretKey: xxxxxxxxxxxx
  endpoint:  http://localhost:9000


